fn main() {
    // MySQL build (default): sqlx uses the standard `.sqlx/` at workspace root — no override needed.
    // PostgreSQL build: point sqlx to `.sqlx-pg/` which contains PG-specific query metadata.
    // `.sqlx-pg/` is generated by running:
    //   DATABASE_URL=postgres://... cargo sqlx prepare --features backend-postgres -- --all-targets
    //   mv .sqlx .sqlx-pg
    if std::env::var("CARGO_FEATURE_BACKEND_POSTGRES").is_ok() {
        let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
        let workspace_root = std::path::Path::new(&manifest_dir).parent().unwrap();
        let sqlx_pg_dir = workspace_root.join(".sqlx-pg");
        println!(
            "cargo:rustc-env=SQLX_OFFLINE_DIR={}",
            sqlx_pg_dir.display()
        );
    }
}
