services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: eddist
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: valkey/valkey:8.0
    container_name: redis_container
    ports:
      - "6379:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8082:80"
    depends_on:
      - mysql
  client-v2:
    image: node:22-bookworm-slim
    container_name: client_v2_container
    working_dir: /workspace
    command: bash -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm -F eddist-client-v2 dev"
    ports:
      - "5173:5173"
    volumes:
      - ..:/workspace
      - pnpm_store:/root/.local/share/pnpm/store
    environment:
      NODE_ENV: development
      PORT: 5173
      CI: "true"
      EDDIST_SERVER_URL: "http://host.docker.internal:8080"
      VITE_PROXY_TARGET: "http://host.docker.internal:8080"
    extra_hosts:
      - "host.docker.internal:${HOST_GATEWAY_IP}"
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client-v2
    extra_hosts:
      - "host.docker.internal:${HOST_GATEWAY_IP}"
volumes:
  mysql_data:
  pnpm_store:
