fn main() {
    println!("cargo:rerun-if-env-changed=DATABASE_URL");
    println!("cargo:rerun-if-env-changed=SQLX_OFFLINE");
    println!("cargo:rerun-if-env-changed=SQLX_OFFLINE_DIR");
    // MySQL build (default): sqlx uses the standard `.sqlx/` at workspace root — no override needed.
    // PostgreSQL build: point sqlx to `.sqlx-pg/` which contains PG-specific query metadata.
    // `.sqlx-pg/` is generated by running:
    //   DATABASE_URL=postgres://... cargo sqlx prepare --features backend-postgres -- --all-targets
    //   mv .sqlx .sqlx-pg
    if std::env::var("CARGO_FEATURE_BACKEND_POSTGRES").is_ok() {
        let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
        let workspace_root = std::path::Path::new(&manifest_dir).parent().unwrap();
        let sqlx_pg_dir = workspace_root.join(".sqlx-pg");
        if std::env::var_os("SQLX_OFFLINE_DIR").is_none() {
            println!("cargo:rustc-env=SQLX_OFFLINE_DIR={}", sqlx_pg_dir.display());
        }
        if std::env::var_os("DATABASE_URL").is_none() && std::env::var_os("SQLX_OFFLINE").is_none()
        {
            println!("cargo:rustc-env=SQLX_OFFLINE=true");
        }
    }
}
