/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/native/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange OAuth2 access token for session token */
        post: operations["post_native_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authed_tokens/{authed_token_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_authed_token"];
        put?: never;
        post?: never;
        delete: operations["delete_authed_token"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_boards"];
        put?: never;
        post: operations["create_board"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{board_key}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_board"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["edit_board"];
        trace?: never;
    };
    "/boards/{board_key}/admin-dat-archives/{thread_number}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_admin_dat_archived_thread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{board_key}/archives/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_archived_threads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{board_key}/archives/{thread_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_archived_thread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{board_key}/archives/{thread_id}/responses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_archived_responses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{board_key}/dat-archives/{thread_number}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_dat_archived_thread"];
        put?: never;
        post?: never;
        delete: operations["delete_archived_thread"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{board_key}/dat-archives/{thread_number}/responses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_archived_res"];
        trace?: never;
    };
    "/boards/{board_key}/dat-archives/{thread_number}/responses/{res_order}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_archived_res"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{board_key}/info/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_board_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{board_key}/threads-compaction/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["threads_compaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{board_key}/threads/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_threads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{board_key}/threads/{thread_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_thread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{board_key}/threads/{thread_id}/responses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_responses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{board_key}/threads/{thread_id}/responses/{res_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_response"];
        trace?: never;
    };
    "/caps/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_caps"];
        put?: never;
        post: operations["create_cap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/caps/{cap_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_cap"];
        options?: never;
        head?: never;
        patch: operations["update_cap"];
        trace?: never;
    };
    "/captcha-configs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_captcha_configs"];
        put?: never;
        post: operations["create_captcha_config"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/captcha-configs/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_captcha_config"];
        put?: never;
        post?: never;
        delete: operations["delete_captcha_config"];
        options?: never;
        head?: never;
        patch: operations["update_captcha_config"];
        trace?: never;
    };
    "/ng_words/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_ng_words"];
        put?: never;
        post: operations["create_ng_word"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ng_words/{ng_word_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_ng_word"];
        options?: never;
        head?: never;
        patch: operations["update_ng_word"];
        trace?: never;
    };
    "/notices/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_notices"];
        put?: never;
        post: operations["create_notice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notices/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_notice"];
        put?: never;
        post?: never;
        delete: operations["delete_notice"];
        options?: never;
        head?: never;
        patch: operations["update_notice"];
        trace?: never;
    };
    "/restriction_rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_restriction_rules"];
        put?: never;
        post: operations["create_restriction_rule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/restriction_rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_restriction_rule"];
        put?: never;
        post?: never;
        delete: operations["delete_restriction_rule"];
        options?: never;
        head?: never;
        patch: operations["update_restriction_rule"];
        trace?: never;
    };
    "/terms/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_terms"];
        put: operations["update_terms"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_user_status"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ArchivedAdminRes: {
            authed_token_id: string;
            author_id?: string | null;
            body: string;
            date: string;
            ip_addr: string;
            mail: string;
            name: string;
        };
        ArchivedAdminThread: {
            responses: components["schemas"]["ArchivedAdminRes"][];
            title: string;
        };
        ArchivedRes: {
            author_id?: string | null;
            body: string;
            date: string;
            is_abone: boolean;
            mail: string;
            name: string;
            /** Format: int64 */
            order: number;
        };
        ArchivedResUpdate: {
            author_name: string;
            body: string;
            email: string;
            /** Format: int64 */
            res_order: number;
        };
        ArchivedThread: {
            responses: components["schemas"]["ArchivedRes"][];
            title: string;
        };
        AuthedToken: {
            additional_info?: unknown;
            /** Format: int32 */
            asn_num: number;
            /** Format: date-time */
            authed_at?: string | null;
            authed_ua?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            last_wrote_at?: string | null;
            origin_ip: string;
            reduced_origin_ip: string;
            token: string;
            validity: boolean;
            writing_ua: string;
        };
        Board: {
            board_key: string;
            default_name: string;
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: int64 */
            thread_count: number;
        };
        BoardInfo: {
            base_response_creation_span_sec: number;
            base_thread_creation_span_sec: number;
            local_rules: string;
            max_author_name_byte_length: number;
            max_email_byte_length: number;
            max_response_body_byte_length: number;
            max_response_body_lines: number;
            max_thread_name_byte_length: number;
            read_only: boolean;
            threads_archive_cron?: string | null;
            threads_archive_trigger_thread_count?: number | null;
        };
        Cap: {
            board_ids: string[];
            /** Format: date-time */
            created_at: string;
            description: string;
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Captcha configuration for API responses */
        CaptchaConfig: {
            base_url?: string | null;
            capture_fields: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: int32 */
            display_order: number;
            /** Format: uuid */
            id: string;
            is_active: boolean;
            name: string;
            provider: string;
            site_key: string;
            /** Format: date-time */
            updated_at: string;
            updated_by?: string | null;
            verification?: null | components["schemas"]["CaptchaVerificationConfig"];
            widget?: null | components["schemas"]["CaptchaWidgetConfig"];
        };
        /** @description Verification API configuration for custom providers */
        CaptchaVerificationConfig: {
            body_template?: string | null;
            headers?: {
                [key: string]: string;
            };
            include_ip?: boolean;
            method?: components["schemas"]["HttpMethod"];
            negate_success?: boolean;
            request_format?: components["schemas"]["RequestFormat"];
            success_path?: string;
            url: string;
        };
        /** @description Widget configuration for frontend rendering */
        CaptchaWidgetConfig: {
            form_field_name: string;
            script_handler?: string | null;
            script_url: string;
            widget_html: string;
        };
        ClientInfo: {
            /** Format: int32 */
            asn_num: number;
            ip_addr: string;
            tinker?: null | components["schemas"]["Tinker"];
            user_agent: string;
        };
        CreateBoardInput: {
            base_response_creation_span_sec?: number | null;
            base_thread_creation_span_sec?: number | null;
            board_key: string;
            default_name: string;
            local_rule: string;
            max_author_name_byte_length?: number | null;
            max_email_byte_length?: number | null;
            max_response_body_byte_length?: number | null;
            max_response_body_lines?: number | null;
            max_thread_name_byte_length?: number | null;
            name: string;
            threads_archive_cron?: string | null;
            threads_archive_trigger_thread_count?: number | null;
        };
        /** @description Input for creating a new captcha config */
        CreateCaptchaConfigInput: {
            base_url?: string | null;
            capture_fields?: string[];
            /** Format: int32 */
            display_order?: number;
            is_active?: boolean;
            name: string;
            provider: string;
            secret: string;
            site_key: string;
            verification?: null | components["schemas"]["CaptchaVerificationConfig"];
            widget?: null | components["schemas"]["CaptchaWidgetConfig"];
        };
        CreateNoticeInput: {
            content: string;
            /** Format: date-time */
            published_at: string;
            slug: string;
            title: string;
        };
        CreateRestrictionRuleRequest: {
            /** Format: date-time */
            expires_at?: string | null;
            name: string;
            rule_type: components["schemas"]["RestrictionRuleTypeSchema"];
            rule_value: string;
        };
        CreationCapInput: {
            description: string;
            name: string;
            password: string;
        };
        CreationNgWordInput: {
            name: string;
            word: string;
        };
        DeleteAuthedTokenInput: {
            using_origin_ip: boolean;
        };
        EditBoardInput: {
            base_response_creation_span_sec?: number | null;
            base_thread_creation_span_sec?: number | null;
            default_name?: string | null;
            local_rule?: string | null;
            max_author_name_byte_length?: number | null;
            max_email_byte_length?: number | null;
            max_response_body_byte_length?: number | null;
            max_response_body_lines?: number | null;
            max_thread_name_byte_length?: number | null;
            name?: string | null;
            read_only?: boolean | null;
            threads_archive_cron?: string | null;
            threads_archive_trigger_thread_count?: number | null;
        };
        /**
         * @description HTTP method for verification requests
         * @enum {string}
         */
        HttpMethod: "Post" | "Get";
        NativeSessionRequest: {
            access_token: string;
        };
        NativeSessionResponse: {
            /** Format: date-time */
            expires_at: string;
            session_token: string;
            user_info: components["schemas"]["NativeUserInfo"];
        };
        NativeUserInfo: {
            email: string;
            email_verified: boolean;
            preferred_username: string;
            sub: string;
        };
        NgWord: {
            board_ids: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date-time */
            updated_at: string;
            word: string;
        };
        /** @description Notice model for API documentation */
        Notice: {
            author_email?: string | null;
            content: string;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            published_at: string;
            slug: string;
            title: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description Request body format for verification API
         * @enum {string}
         */
        RequestFormat: "Form" | "Json" | "PlainText";
        Res: {
            /** Format: uuid */
            authed_token_id: string;
            author_id: string;
            author_name?: string | null;
            /** Format: uuid */
            board_id: string;
            body: string;
            client_info: components["schemas"]["ClientInfo"];
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            ip_addr: string;
            is_abone: boolean;
            mail?: string | null;
            /** Format: int32 */
            res_order: number;
            /** Format: uuid */
            thread_id: string;
        };
        /** @enum {string} */
        RestrictionRuleTypeSchema: "Asn" | "IP" | "IPCidr" | "UserAgent";
        /** @description Terms model for API documentation */
        Terms: {
            content: string;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            updated_at: string;
            updated_by?: string | null;
        };
        Thread: {
            active: boolean;
            archived: boolean;
            /** Format: uuid */
            authed_token_id: string;
            /** Format: uuid */
            board_id: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            last_modified: string;
            metadent: string;
            no_pool: boolean;
            /** Format: int32 */
            response_count: number;
            /** Format: date-time */
            sage_last_modified: string;
            /** Format: int64 */
            thread_number: number;
            title: string;
        };
        ThreadCompactionInput: {
            /** Format: int32 */
            target_count: number;
        };
        Tinker: {
            authed_token: string;
            /** Format: int32 */
            created_thread_count: number;
            /** Format: int64 */
            last_created_thread_at?: number | null;
            /** Format: int64 */
            last_level_up_at: number;
            /** Format: int64 */
            last_wrote_at: number;
            /** Format: int32 */
            level: number;
            /** Format: int32 */
            wrote_count: number;
        };
        UpdateCapInput: {
            board_ids?: string[] | null;
            description?: string | null;
            name?: string | null;
            password?: string | null;
        };
        /** @description Input for updating an existing captcha config */
        UpdateCaptchaConfigInput: {
            base_url?: string | null;
            capture_fields?: string[] | null;
            /** Format: int32 */
            display_order?: number | null;
            is_active?: boolean | null;
            name?: string | null;
            provider?: string | null;
            secret?: string | null;
            site_key?: string | null;
            verification?: null | components["schemas"]["CaptchaVerificationConfig"];
            widget?: null | components["schemas"]["CaptchaWidgetConfig"];
        };
        UpdateNgWordInput: {
            board_ids?: string[] | null;
            name?: string | null;
            word?: string | null;
        };
        UpdateNoticeInput: {
            content?: string | null;
            /** Format: date-time */
            published_at?: string | null;
            /** @description Optional custom slug. If not provided and title is updated, will be auto-generated from new title. */
            slug?: string | null;
            title?: string | null;
        };
        UpdateResInput: {
            author_name?: string | null;
            body?: string | null;
            is_abone?: boolean | null;
            mail?: string | null;
        };
        UpdateRestrictionRuleRequest: {
            /** Format: date-time */
            expires_at?: string | null;
            name?: string | null;
            rule_type?: null | components["schemas"]["RestrictionRuleTypeSchema"];
            rule_value?: string | null;
        };
        UpdateTermsInput: {
            content: string;
        };
        User: {
            authed_token_ids: string[];
            enabled: boolean;
            /** Format: uuid */
            id: string;
            idp_bindings: components["schemas"]["UserIdpBinding"][];
            user_name: string;
        };
        UserIdpBinding: {
            /** Format: uuid */
            id: string;
            idp_name: string;
            idp_sub: string;
            /** Format: uuid */
            user_id: string;
        };
        UserRestrictionRuleSchema: {
            /** Format: date-time */
            created_at: string;
            created_by_email: string;
            /** Format: date-time */
            expires_at?: string | null;
            id: string;
            name: string;
            rule_type: components["schemas"]["RestrictionRuleTypeSchema"];
            rule_value: string;
            /** Format: date-time */
            updated_at: string;
        };
        UserSearchQuery: {
            /** Format: uuid */
            authed_token_id?: string | null;
            /** Format: uuid */
            user_id?: string | null;
            user_name?: string | null;
        };
        UserStatusUpdateInput: {
            enabled: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_native_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NativeSessionRequest"];
            };
        };
        responses: {
            /** @description Session token created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NativeSessionResponse"];
                };
            };
            /** @description Invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_authed_token: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Authed token ID */
                authed_token_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get authed token successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthedToken"];
                };
            };
        };
    };
    delete_authed_token: {
        parameters: {
            query: {
                using_origin_ip: boolean;
            };
            header?: never;
            path: {
                /** @description Authed token ID */
                authed_token_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete authed token successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_boards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List boards successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"][];
                };
            };
        };
    };
    create_board: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBoardInput"];
            };
        };
        responses: {
            /** @description Create board successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateBoardInput"];
                };
            };
        };
    };
    get_board: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Board ID */
                board_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get board successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
            /** @description Board not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    edit_board: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Board Key */
                board_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditBoardInput"];
            };
        };
        responses: {
            /** @description Edit board successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
        };
    };
    get_admin_dat_archived_thread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Board ID */
                board_key: string;
                /** @description Thread ID */
                thread_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get archived thread successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchivedAdminThread"];
                };
            };
        };
    };
    get_archived_threads: {
        parameters: {
            query?: {
                keyword?: string | null;
                start?: number | null;
                end?: number | null;
                page?: number | null;
                limit?: number | null;
            };
            header?: never;
            path: {
                /** @description Board ID */
                board_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List threads successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"][];
                };
            };
        };
    };
    get_archived_thread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Board ID */
                board_key: string;
                /** @description Thread ID */
                thread_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get thread successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"];
                };
            };
            /** @description Thread not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_archived_responses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Thread ID */
                thread_id: number;
                board_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List responses successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Res"][];
                };
            };
            /** @description Thread not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_dat_archived_thread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Board ID */
                board_key: string;
                /** @description Thread ID */
                thread_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get archived thread successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchivedThread"];
                };
            };
        };
    };
    delete_archived_thread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Board ID */
                board_key: string;
                /** @description Thread ID */
                thread_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete thread successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_archived_res: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Board ID */
                board_key: string;
                /** @description Thread ID */
                thread_number: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchivedResUpdate"][];
            };
        };
        responses: {
            /** @description Update archived response successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    delete_archived_res: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Board ID */
                board_key: string;
                /** @description Thread ID */
                thread_number: number;
                /** @description Response order */
                res_order: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete response successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_board_info: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Board ID */
                board_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get board info successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardInfo"];
                };
            };
            /** @description Board not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    threads_compaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Board Key */
                board_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThreadCompactionInput"];
            };
        };
        responses: {
            /** @description Compaction thread successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_threads: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List threads successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"][];
                };
            };
        };
    };
    get_thread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Board ID */
                board_key: string;
                /** @description Thread ID */
                thread_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get thread successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"];
                };
            };
            /** @description Thread not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_responses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Thread ID */
                thread_id: number;
                board_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List responses successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Res"][];
                };
            };
            /** @description Thread not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_response: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Board ID */
                board_key: string;
                /** @description Thread ID */
                thread_id: number;
                /** @description Response ID */
                res_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateResInput"];
            };
        };
        responses: {
            /** @description Update response successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Res"];
                };
            };
        };
    };
    get_caps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List cap words successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cap"][];
                };
            };
        };
    };
    create_cap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreationCapInput"];
            };
        };
        responses: {
            /** @description Create cap successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cap"];
                };
            };
        };
    };
    delete_cap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cap ID */
                cap_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete Cap successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_cap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cap ID */
                cap_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCapInput"];
            };
        };
        responses: {
            /** @description Update cap word successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cap"];
                };
            };
        };
    };
    list_captcha_configs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List all captcha configs successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptchaConfig"][];
                };
            };
        };
    };
    create_captcha_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCaptchaConfigInput"];
            };
        };
        responses: {
            /** @description Captcha config created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptchaConfig"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_captcha_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Captcha config ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get captcha config successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptchaConfig"];
                };
            };
            /** @description Captcha config not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_captcha_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Captcha config ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Captcha config deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Captcha config not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_captcha_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Captcha config ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCaptchaConfigInput"];
            };
        };
        responses: {
            /** @description Captcha config updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptchaConfig"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Captcha config not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_ng_words: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List ng words successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NgWord"][];
                };
            };
        };
    };
    create_ng_word: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreationNgWordInput"];
            };
        };
        responses: {
            /** @description Create ng word successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NgWord"];
                };
            };
        };
    };
    delete_ng_word: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description NG word ID */
                ng_word_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete ng word successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_ng_word: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description NG word ID */
                ng_word_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNgWordInput"];
            };
        };
        responses: {
            /** @description Update ng word successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NgWord"];
                };
            };
        };
    };
    get_notices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List notices successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notice"][];
                };
            };
        };
    };
    create_notice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNoticeInput"];
            };
        };
        responses: {
            /** @description Notice created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notice"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_notice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Notice ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get notice successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notice"];
                };
            };
            /** @description Notice not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_notice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Notice ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notice deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not the notice author */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Notice not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_notice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Notice ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNoticeInput"];
            };
        };
        responses: {
            /** @description Notice updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notice"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not the notice author */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Notice not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_restriction_rules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List all restriction rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRestrictionRuleSchema"][];
                };
            };
        };
    };
    create_restriction_rule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRestrictionRuleRequest"];
            };
        };
        responses: {
            /** @description Create restriction rule */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRestrictionRuleSchema"];
                };
            };
        };
    };
    get_restriction_rule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Rule ID */
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get restriction rule by ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRestrictionRuleSchema"];
                };
            };
        };
    };
    delete_restriction_rule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Rule ID */
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete restriction rule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_restriction_rule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Rule ID */
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRestrictionRuleRequest"];
            };
        };
        responses: {
            /** @description Update restriction rule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_terms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get terms successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Terms"];
                };
            };
            /** @description Terms not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_terms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTermsInput"];
            };
        };
        responses: {
            /** @description Terms updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Terms"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Terms not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search_users: {
        parameters: {
            query?: {
                user_id?: string | null;
                user_name?: string | null;
                authed_token_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List users successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    update_user_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserStatusUpdateInput"];
            };
        };
        responses: {
            /** @description Update user status successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
}
