name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v2
      - name: Load cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --release
      - name: rm .dockerignore
        run: rm .dockerignore
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker-prod/Dockerfile
          push: true
          tags: |
            ghcr.io/edginer/eddist:${{ github.sha }}
            ghcr.io/edginer/eddist:latest
      - name: notify deploy server
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DEPLOY_REPO_PAT }}
          repository: ${{ secrets.DEPLOY_REPO_URL }}
          event-type: update-image
          client-payload: '{"image-tag": "${{ github.sha }}"}'
