name: CI

on:
  push:
    branches:
      - main

jobs:
  build-eddist:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      VITE_EDDIST_ADMIN_AUTH_SERVER_URL: ${{ secrets.VITE_EDDIST_ADMIN_AUTH_SERVER_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v2
      - name: Load cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
          version: "latest"
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: |
            "pnpm-lock.yaml"
            "eddist/client/pnpm-lock.yaml"
            "eddist-admin/client/pnpm-lock.yaml"
      - name: Install pnpm dependencies
        run: pnpm install
      - name: Build eddist-client
        run: pnpm -F eddist-client build
      - name: Build eddist-admin-client
        run: pnpm -F eddist-admin-client build
      - name: Build
        run: cargo build --release
      - name: rm .dockerignore
        run: rm .dockerignore
      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (eddist)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker-prod/eddist/Dockerfile
          push: true
          tags: |
            ghcr.io/edginer/eddist:${{ github.sha }}
            ghcr.io/edginer/eddist:latest
      - name: Build and push Docker image (eddist-admin)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker-prod/eddist-admin/Dockerfile
          push: true
          tags: |
            ghcr.io/edginer/eddist-admin:${{ github.sha }}
            ghcr.io/edginer/eddist-admin:latest
      - name: Build and push Docker image (eddist-cron)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker-prod/eddist-cron/Dockerfile
          push: true
          tags: |
            ghcr.io/edginer/eddist-cron:${{ github.sha }}
            ghcr.io/edginer/eddist-cron:latest
      - name: notify deploy server
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DEPLOY_REPO_PAT }}
          repository: ${{ secrets.DEPLOY_REPO_URL }}
          event-type: update-image
          client-payload: '{"image-tag": "${{ github.sha }}"}'
