[package]
name = "eddist-cron"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
sea-orm.workspace = true
anyhow.workspace = true
cron.workspace = true
chrono.workspace = true
serde_json.workspace = true
eddist-core.workspace = true
eddist-entity.workspace = true
aws-sdk-s3.workspace = true
uuid.workspace = true
dotenvy.workspace = true
redis = { workspace = true, features = ["connection-manager"] }
log.workspace = true
encoding_rs = { workspace = true, features = ["fast-kanji-encode"] }
rand.workspace = true
futures.workspace = true

[dev-dependencies]
sqlx = { workspace = true, features = ["migrate"] }
testcontainers.workspace = true
testcontainers-modules.workspace = true
